server:
  port: 9001
  servlet:
    context-path: /system
spring:
  application:
    name: yoga-system
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #解决关于documentationPluginsBootstrapper空指针问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/yoga?useUnicode=true&characterEncoding=UTF-8
    username: **
    password: ***
  redis:
    host: *.*.*.*
    port: 6379
    password: **
    database: 0


  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

swagger:
  groupName: yoga-system
  enabled: true
  title: yoga-system
  description: "系统服务"
  version: 1.0
  license: "执照"
  licenseUrl: http://baidu.com
  terms-of-service-url: http://baidu.com
  contact:
    name: tao
    email: 111111
    url: http://baidu.com
  authorization:
    name: http://baidu.com
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false





qiniu:
  access-key: **
  secret-key: ****
  bucket: *****
  region: ****
  domain-of-bucket: http://qiniu.*.*/
  expire-in-seconds: -1

